---
# tasks file for orita.bamboo

- name: create bamboo user
  user: name=bamboo comment="Bamboo role account"

- name: create bamboo base dir
  file: path={{ bamboo_basedir }} mode=0755 owner=bamboo group=bamboo state=directory

- name: create bamboo home dir
  file: path={{ bamboo_homedir }} mode=0755 owner=bamboo group=bamboo state=directory

- name: get bamboo tarball
  get_url: url={{ bamboo_binary_url }} dest=/tmp
  register: bamboo_geturl

- name: put bamboo tarball
  unarchive: src={{ bamboo_geturl.dest }} dest={{ bamboo_basedir }} copy=no owner=bamboo group=bamboo

- name: check bamboo tarball top dir
  shell: tar tzf {{ bamboo_geturl.dest }} | head -1 | tr -d /
  register: bamboo_original_bindir
  ignore_errors: True
  changed_when: "bamboo_original_bindir.rc != 0"

- name: link bamboo binary
  file: src={{ bamboo_basedir }}/{{ bamboo_original_bindir.stdout }} dest={{ bamboo_basedir }}/current state=link

- name: initscript bamboo
  template: src=initscript_bamboo dest=/etc/init.d/bamboo mode=0755

- name: set bamboo_home
  lineinfile: dest={{ bamboo_basedir }}/current/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties line='bamboo.home={{ bamboo_homedir }}' state=present

- name: enable bamboo service
  service: name=bamboo enabled=yes state=started
